apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant.name }}-myapp
  namespace: {{ .Values.tenant.namespace }}
  labels:
    app: myapp
    tenant: {{ .Values.tenant.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
    tenant: {{ .Values.tenant.name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP

